[package]
name = "mashmap"
version = "0.1.0"
authors = ["Igor Martayan <imartayan@users.noreply.github.com>"]
description = "A flat HashMap that supports multiple entries per key"
edition = "2021"

[dependencies]
ahash = "0.8"
hashbrown = { version = "0.14", features = ["raw"] }
